jobs:
  build:
    name: Action
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Prerequisites
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Check
        run: ./main/verify

name: Verify

on:
  schedule:
    - cron: "10 */6 * * *"
